"""
train_cnn.py

Trains the inpainting network of cnn_estimator.py on simulator data, and saves its weights.

The training pairs are disease fields (TYLCV and CCR) of Miniberry-30 farms with random seeds, days and 
plantings, with the observations of random samples and of random-waypoint trajectories of random lengths, 
generated by the samplers of the estimator benchmark. The ground truth of the experiments (environment 
seed 10) is excluded, so that the benchmark evaluates the network on unseen environments.

    python -m papers.estimator_cnn.train_cnn --samples 600 --epochs 40
"""

import argparse
import pathlib
import sys

import numpy as np
import torch
from torch import nn

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from estimator_benchmark import generate_observations
from papers.estimator_cnn.cnn_estimator import InpaintingNet, input_planes
from water_berry_farm import MiniberryFarm, WaterberryFarmEnvironment


def training_pairs(samples, seed):
    """(inputs, diseased, values) arrays for samples environments x 2 disease fields"""
    random = np.random.default_rng(seed)
    inputs, diseased, values = [], [], []
    for i in range(samples):
        farm = MiniberryFarm(scale=3)
        farm.replant(random.choice(["standard", "tomato-only"]))
        farm.create_type_map()
        environment = WaterberryFarmEnvironment(farm, use_saved=False, seed=1000 + i, savedir=None)
        environment.proceed(int(random.integers(3, 13)))
        if random.random() < 0.5:
            sampler = {"kind": "random", "count": int(random.integers(20, 300))}
        else:
            sampler = {"kind": "random-waypoint", "timesteps": int(random.integers(50, 400))}
        observations = generate_observations(sampler, environment, "Miniberry-30", int(random.integers(1 << 30)))
        for name, key in [("tylcv", "TYLCV"), ("ccr", "CCR")]:
            truth = getattr(environment, name).value
            inputs.append(input_planes([o[key] for o in observations], 30, 30))
            diseased.append(truth < 0.75)
            values.append(truth)
    return (torch.tensor(np.array(inputs)), torch.tensor(np.array(diseased), dtype=torch.float32),
            torch.tensor(np.array(values), dtype=torch.float32))


def train(samples, epochs, seed, output):
    torch.manual_seed(seed)
    inputs, diseased, values = training_pairs(samples, seed)
    model = InpaintingNet()
    optimizer = torch.optim.Adam(model.parameters(), lr=2e-3)
    for epoch in range(epochs):
        permutation = torch.randperm(len(inputs))
        total = 0.0
        for batch in permutation.split(32):
            output_planes = model(inputs[batch])
            loss = (nn.functional.binary_cross_entropy_with_logits(output_planes[:, 0], diseased[batch])
                    + nn.functional.mse_loss(torch.sigmoid(output_planes[:, 1]), values[batch]))
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total += loss.item() * len(batch)
        print(f"epoch {epoch}: loss {total / len(inputs):.4f}")
    torch.save(model.state_dict(), output)
    print(f"saved {output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=int, default=600)
    parser.add_argument("--epochs", type=int, default=40)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--output", default=str(pathlib.Path(__file__).resolve().parent / "cnn.pt"))
    arguments = parser.parse_args()
    train(arguments.samples, arguments.epochs, arguments.seed, arguments.output)
